### ISSUE TITLE
lodash Prototype Pollution Vulnerability

### ISSUE THREAD

**Issue by zavalyshyn** [mmaelzer/mjpeg-camera#10]
The Lodash library has been found to be vulnerable to Prototype Pollution attack.
npm advises an update to the latest library version.

Do you think it will require a lot of effort? 

I tried running 'npm audit fix' but apparently the patch causes breaking changes in mjpeg-camera code.

**Comment by mmaelzer** [comment]
Thanks for raising this issue! I'd be happy to take a pull request for this fix. It should only take 2 small changes to remove the lodash dependency:

Replace [line 29](https://github.com/mmaelzer/mjpeg-camera/blob/master/mjpeg-camera.js#L35) with
```javascript
this.name = options.name || ('camera' + (Math.floor(Math.random() * 1000)));
```
Replace [line 35](https://github.com/mmaelzer/mjpeg-camera/blob/master/mjpeg-camera.js#L35) with
```javascript
this.sendImmediately = 'sendImmediately' in options ? options.sendImmediately : true;
```
After those changes, you should be able to remove the dependency on lodash and this would no longer be an issue.

**Comment by mmaelzer** [comment]
I went ahead and fixed this as there was another issue in [mjpeg-consumer](https://github.com/mmaelzer/mjpeg-consumer) that I wanted to bring into this library.

**Comment by zavalyshyn** [comment]
Wow, just when I wanted to contribute somehow :) Thanks a lot!

**Comment by mmaelzer** [comment]
If you run across issues in any of my other libraries, I'm always happy to take pull requests. Additionally, if you want to improve `mjpeg-camera`, it could certainly use some tests. The tests for [mjpeg-consumer](https://github.com/mmaelzer/mjpeg-consumer) would be a great starting point for `mjpeg-camera` tests.
