### ISSUE TITLE
keepalive called after connection.abort() resulting in error.

### ISSUE THREAD

**Issue by vill3m647** [mmaelzer/mjpeg-camera#15]
When camera.stop() is called and the connection is aborted then keepalive is called by this line: 
`this.connection.on('error', this.keepalive.bind(this));` 
and so when stop() is called again in `keepalive()` it tries to abort the connection that has already been aborted and set to `null`
resulting in error: `TypeError: Cannot read properties of null (reading 'abort')`

Using Node v16.14.2

**Comment by mmaelzer** [comment]
Thanks for filing this issue. It should be fixed now.
