### ISSUE TITLE
Loading forever, black screen.

### ISSUE THREAD

**Issue by drptbl** [mmaelzer/mjpeg-camera#7]
Like in title.
Tested on Win7 x64, MAC OS - same behaviour for both.

Node 5.0.0
Npm 3.3.6

No issues when installing.

Steps to reproduce:
npm install mjpeg-camera -g
cs -l http://10.53.2.43/ -p 12345
http://10.53.2.43:12345/
![screen shot 2016-03-21 at 13 08 59](https://cloud.githubusercontent.com/assets/8177587/13918242/2d07dbc6-ef66-11e5-8930-c93294c977b4.png)

**Comment by mmaelzer** [comment]
The `-l` flag is to provide the url of the camera, not the web server. Calling `cs -l http://10.53.2.43/ -p 12345` means: connect to an mjpeg camera at `10.53.2.43`, proxy its stream to an http page hosted at the local ip address on port `12345`.

Hopefully this helps.

**Comment by drptbl** [comment]
Close please.
