### ISSUE TITLE
Video Recording

### ISSUE THREAD

**Issue by crosofg** [mmaelzer/mjpeg-camera#8]
How do I record videos through this?

**Comment by mmaelzer** [comment]
If you wanted to create a video, you could use the jpegs generated by mjpeg-camera and pass them to ffmpeg which could create the desired video file(s).

Some links that might help you out:
http://superuser.com/questions/624567/ffmpeg-create-a-video-from-images
http://electron.mit.edu/~gsteele/ffmpeg/
http://stackoverflow.com/questions/13294919/can-you-stream-images-to-ffmpeg-to-construct-a-video-instead-of-saving-them-t
